import React, { useEffect, useRef } from "react";
import { View, Text, StyleSheet } from "react-native";
import type { NativeStackScreenProps } from "@react-navigation/native-stack";
import type { RootStackParamList } from "../AppNavigator";
import { useSessionStore } from "../store/useSessionStore";
import { ZodiacLogoRing } from "../components/ZodiacLogoRing";
import { bootstrapSessionProfile } from "../services/session";
import { loadTermsConsent } from "../services/consent";
import { firebaseAuth } from "../services/firebase";

type Props = NativeStackScreenProps<RootStackParamList, "Splash">;

const PRIMARY = "#7f13ec";
const BACKGROUND_DARK = "#191022";

export const SplashScreen: React.FC<Props> = ({ navigation }) => {
  const token = useSessionStore((s) => s.token);
  const zodiacSign = useSessionStore((s) => s.zodiacSign);
  const termsAccepted = useSessionStore((s) => s.termsAccepted);
  const consentLoaded = useSessionStore((s) => s.consentLoaded);
  const setAuth = useSessionStore((s) => s.setAuth);
  const setZodiacSign = useSessionStore((s) => s.setZodiacSign);
  const setTermsAccepted = useSessionStore((s) => s.setTermsAccepted);
  const setConsentLoaded = useSessionStore((s) => s.setConsentLoaded);
  const hasNavigated = useRef(false);

  useEffect(() => {
    if (hasNavigated.current) return;

    const navigateToDestination = (hasAuth: boolean) => {
      if (hasNavigated.current) return;
      hasNavigated.current = true;
      if (!hasAuth) {
        navigation.replace("Auth");
      } else if (!zodiacSign) {
        navigation.replace("Onboarding");
      } else {
        navigation.replace("Main");
      }
    };

    const run = async () => {
      let accepted = termsAccepted;
      if (!consentLoaded) {
        accepted = await loadTermsConsent();
        setTermsAccepted(accepted);
        setConsentLoaded(true);
      }

      let hasAuth = !!token;
      const resolvedZodiacSign = zodiacSign;
      const currentUser = firebaseAuth.currentUser;
      if (currentUser && !token) {
        try {
          const jwt = await currentUser.getIdToken();
          if (jwt) {
            setAuth({ clerkUserId: currentUser.uid, token: jwt });
            // Do not block navigation on network/bootstrap.
            void bootstrapSessionProfile({
              clerkUserId: currentUser.uid,
              token: jwt,
              email: currentUser.email ?? "",
              fullName: currentUser.displayName ?? "",
              avatarUrl: currentUser.photoURL ?? undefined,
            })
              .then((profile) => {
                setZodiacSign(profile.zodiacSign);
              })
              .catch(() => {
                // ignore bootstrap errors at startup
              });
            hasAuth = true;
          }
        } catch {
          // ignore
        }
      } else if (currentUser && token) {
        hasAuth = true;
        // Do not block navigation on network/bootstrap.
        void bootstrapSessionProfile({
          clerkUserId: currentUser.uid,
          token,
          email: currentUser.email ?? "",
          fullName: currentUser.displayName ?? "",
          avatarUrl: currentUser.photoURL ?? undefined,
        })
          .then((profile) => {
            setZodiacSign(profile.zodiacSign);
          })
          .catch(() => {
            // ignore bootstrap errors at startup
          });
      }

      if (currentUser || hasAuth) {
        if (hasAuth) {
          if (hasNavigated.current) return;
          hasNavigated.current = true;
          if (!accepted) {
            navigation.replace("Auth");
            return;
          }
          if (!resolvedZodiacSign) {
            navigation.replace("Onboarding");
          } else {
            navigation.replace("Main");
          }
          return;
        }
        navigateToDestination(false);
        return;
      }

      // No auth state present: navigate immediately.
      if (hasNavigated.current) return;
      hasNavigated.current = true;
      navigation.replace("Auth");
    };

    run();
  }, [token, zodiacSign, termsAccepted, consentLoaded, navigation, setAuth, setZodiacSign, setTermsAccepted, setConsentLoaded]);

  return (
    <View style={styles.container}>
      <View style={styles.gradient}>
        {/* Top bar icon */}
        <View style={styles.topBar}>
          <Text style={styles.topIcon}>✦</Text>
        </View>

        {/* Main: celestial logo + zodiac ring */}
        <View style={styles.main}>
          <ZodiacLogoRing />

          {/* Typography */}
          <View style={styles.typography}>
            <Text style={styles.title}>AstraDaily</Text>
            <Text style={styles.subtitle}>Daily Horoscope generated by AI</Text>
          </View>
        </View>

        {/* Loading */}
        <View style={styles.loadingSection}>
          <Text style={styles.loadingLabel}>Consulting the Stars</Text>
          <View style={styles.loadingBarBg}>
            <View style={styles.loadingBarFill} />
          </View>
        </View>

        {/* Footer */}
        <View style={styles.footer}>
          <Text style={styles.disclaimer}>
            Ai-generated for entertainment only. Not a substitute for professional advice.
          </Text>
          <Text style={styles.copyright}>© 2026 AstraDaily • Cosmic Intelligence</Text>
        </View>

        {/* Decorative */}
        <View style={[styles.decor, styles.decor1]}>
          <Text style={styles.decorIcon}>✶</Text>
        </View>
        <View style={[styles.decor, styles.decor2]}>
          <Text style={styles.decorIcon2}>✺</Text>
        </View>
        <View style={[styles.decor, styles.decor3]}>
          <Text style={styles.decorIcon3}>✹</Text>
        </View>
      </View>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: BACKGROUND_DARK,
  },
  gradient: {
    flex: 1,
    backgroundColor: "#0f0a1a",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  topBar: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    flexDirection: "row",
    justifyContent: "flex-end",
    padding: 16,
    zIndex: 10,
  },
  topIcon: {
    fontSize: 24,
    color: "rgba(127, 19, 236, 0.4)",
  },
  main: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
    maxWidth: 400,
  },
  typography: {
    alignItems: "center",
    marginTop: 48,
  },
  title: {
    fontSize: 42,
    fontWeight: "700",
    letterSpacing: -0.5,
    color: "#f1f5f9",
  },
  subtitle: {
    marginTop: 8,
    fontSize: 16,
    fontWeight: "500",
    letterSpacing: 6,
    color: "rgba(127, 19, 236, 0.7)",
    textTransform: "uppercase",
    textAlign: "center",
  },
  loadingSection: {
    width: "100%",
    maxWidth: 320,
    paddingHorizontal: 32,
    paddingBottom: 80,
    alignSelf: "center",
  },
  loadingLabel: {
    fontSize: 11,
    fontWeight: "500",
    letterSpacing: 4,
    color: "#94a3b8",
    textTransform: "uppercase",
    textAlign: "center",
    marginBottom: 12,
  },
  loadingBarBg: {
    height: 4,
    width: "100%",
    borderRadius: 2,
    backgroundColor: "rgba(127, 19, 236, 0.1)",
    overflow: "hidden",
  },
  loadingBarFill: {
    height: "100%",
    width: "45%",
    borderRadius: 2,
    backgroundColor: PRIMARY,
  },
  footer: {
    position: "absolute",
    bottom: 24,
    left: 0,
    right: 0,
    alignItems: "center",
    paddingHorizontal: 16,
  },
  disclaimer: {
    fontSize: 10,
    color: "rgba(148, 163, 184, 0.6)",
    textAlign: "center",
    marginBottom: 8,
  },
  copyright: {
    fontSize: 12,
    color: "rgba(100, 116, 139, 0.5)",
  },
  decor: {
    position: "absolute",
  },
  decor1: {
    top: 80,
    left: 40,
    opacity: 0.2,
  },
  decor2: {
    top: "33%",
    right: 48,
    opacity: 0.1,
  },
  decor3: {
    bottom: "25%",
    left: 64,
    opacity: 0.15,
  },
  decorIcon: {
    fontSize: 20,
    color: PRIMARY,
  },
  decorIcon2: {
    fontSize: 36,
    color: PRIMARY,
  },
  decorIcon3: {
    fontSize: 24,
    color: PRIMARY,
  },
});
